### ISSUE TITLE
Error running engine on OSX Big Sur 11.2.1

### ISSUE THREAD

**Issue by drewwyatt** [asimmon/bomberjam-contest#15]
# What I did

- downloaded [bomberjam-starter-kits-osx-x64 (run#798261604)](https://github.com/asimmon/bomberjam-contest/suites/2619062000/artifacts/57389470)
- ran `chmod +x` on `engine/bomberjam` and `starters/Javascript/run_game.sh`
- ran `./run_game.sh` from the `starters/Javascript` directory

# What happened

```
$ ./run_game.sh                                                         137 ↵
Unhandled exception. System.Exception: Failed to start the process 'node MyBot.js --logging'
 ---> System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Bomberjam.BotProcess.Start()
   --- End of inner exception stack trace ---
   at Bomberjam.BotProcess.Start()
   at Bomberjam.Worker.CreateProcesses()
   at Bomberjam.Worker.Work()
   at Bomberjam.Program.Main(String[] args)
./run_game.sh: line 3: 34651 Abort trap: 6           ../../engine/bomberjam --output replay.json "node MyBot.js --logging" "node MyBot.js" "node MyBot.js" "node MyBot.js"
```

**Comment by html5-ninja** [comment]
same here

**Comment by asimmon** [comment]
Thanks for reporting this, I've updated the download link on the website!
